/*
** // Application State - Generated by reducers
** {
**  book: [{title: 'Harry Potter', {title: 'Javascript'}}],   // Books Reducer
**  activeBook: {title: 'Javascript: The Good Parts'}     // ActiveBook Reducer
** }
*/
import { combineReducers } from 'redux';
import BooksReducer from './reducer_books';
import ActiveBook from './reducer_active_book';

const rootReducer = combineReducers({
  books: BooksReducer,
  activeBook: ActiveBook
});

export default rootReducer;
